### ISSUE TITLE
wrong id_rsa applied

### ISSUE THREAD

**Issue by MDykstra** [mate-desktop-legacy-archive/libmatekeyring#6]
Having several SSH 'id_rsa' keys for GitHub loaded (visible in Seahorse showing MATE keyring). Having e-mail of one 'id_rsa' account set in '~/.gitconfig' through '[user] email ='. 

When pushing to GitHub the wrong 'id_rsa' key is applied (the first one showing up in 'ssh-add -l').
Not the one asked for by 'git push' through '~/.gitconfig'.

When doing the same on a different TTY (outside Mate session), using 'ssh-agent' to provide the 'id_rsa' key there is no problem.

**Comment by raveit65** [comment]
mate-keyring is obsolete with mate-1.8 ;)
I suggest to use gnome-keyring.

**Comment by MarcelDykstra** [comment]
Maybe I should have submitted the issue in mate-terminal; where I executed the Git command. I should think a bit better how the key is provided to Git and what makes it different from just executing it in TTY. I will try gnome-terminal inside MATE next time I make a commit.

**Comment by MDykstra** [comment]
Maybe I should have submitted this issue in mate-terminal, where I executed the Git command. I should think a bit better how the key is provided to Git and what makes it different for executing just in TTY. I am currently using gnome-keyring. Bit confusing these deprecated repos.
